Add Form-check component
julieg18/iterative-landing pull request #13
Opened 2021-01-15 16:50 UTC by iceicery

Custom checkbox is harder than I think. I followed the link below. 
https://www.w3schools.com/howto/howto_css_custom_checkbox.asp

2021-01-15 19:04 UTC, julieg18 commented on src/components/Form-check/Form-check.css
> +.formcheck {
Your component file appears to be Form-check, wouldn't FormCheck be a more accurate name?

2021-01-15 19:06 UTC, julieg18 commented on src/components/Form-check/Form-check.css
> +.formcheck__text {
It would be a good idea to give `.formcheck__text` a color of black, since the site is going to automatically apply it a color of white.

2021-01-15 19:12 UTC, julieg18 commented on src/components/Form-check/Form-check.css
> +
Along with connecting the buttons to the input:checked, you need to give the buttons `outline: auto` when input is focused on.(`input:focus`)

2021-01-15 19:25 UTC, julieg18 commented on src/components/Form-check/Form-check.js
> +      <input type="checkbox" className="formcheck__input" />
I believe if the shape is circle, this input needs to be a radio.

2021-01-15 19:29 UTC, julieg18 commented on src/components/Form-check/Form-check.js
> +
We're probably going to implement some kind of onChange prop, just in case we need to connect the current value with form validation. But we can do that once we know more about how we are going to implement our form.

2021-01-15 19:31 UTC, julieg18 commented on src/components/Form-check/Form-check.js
> +
```
function onKeyUp(e) {
    if (e.key === 'Enter') {
      e.target.click();
    }
  }

<input onKeyUp={onKeyUp}...
```
You'll should implement a onKeyUp function for accessibility.

2021-01-15 19:44 UTC, julieg18 requested changes
The styling is amazing! You did an great job! I made quite a few comments mostly about making the inputs more accessible for users. Feel free to ask me about anything I mentioned!

2021-01-15 23:00 UTC, iceicery commented on src/components/Form-check/Form-check.js
> +      <input type="checkbox" className="formcheck__input" />
https://www.geeksforgeeks.org/radio-button-vs-checkbox-in-html/
I thought it is more about one option v.s many options but never noticed the shape.  Since Figma shows checkbox/ radio, I believe they want both. Thanks for pointing out,

2021-01-16 02:01 UTC, iceicery commented on src/components/Form-check/Form-check.js
> +
That's a good idea. Thank you for offering the code.

2021-01-16 06:32 UTC, julieg18 commented on src/components/FormCheck/FormCheck.css
> +  line-height: 20px;
The font color is placed in one of the media queries instead of the original declaration.

2021-01-16 06:36 UTC, julieg18 requested changes
You did a awesome job changing everything I mentioned! Once you fix the typos, I can approve!

2021-01-16 06:40 UTC, julieg18 commented on src/components/FormCheck/FormCheck.css
> +  border: 2px solid #13adc7;
Shouldn't this border be wider?

2021-01-16 15:05 UTC, iceicery commented on src/components/FormCheck/FormCheck.css
> +  border: 2px solid #13adc7;
Thanks for catching that. Fixed!

2021-01-17 00:08 UTC, julieg18 approved these changes
Great job!

2021-01-17 00:10 UTC, merged