Add Avatar component
julieg18/iterative-landing pull request #15
Opened 2021-01-16 23:27 UTC by iceicery

This Avatar component could be used for square and circle avatar.

2021-01-17 04:55 UTC, julieg18 requested changes
Brilliant job so far! I love the idea of not just exporting the entire image with the border, but creating your own! There is couple of things that need to be fixed and I gave some code suggestions. As always, message me if you have any questions about my comments!

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +}
There should be a space after this declaration.

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +        <div className="avatar-square">
Should this be `avatar__square` since it's part of the avatar block?

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +          <div className="avatar__item"><div style={{ backgroundImage: `url(${image})` }} className="avatar__item-img"></div></div>
Is there a way to turn this into an img instead of a background image? Then we could have an `alt` attribute for accessibility. But you would have to add a prop for a alt text... Feel free to discuss this with me 😃

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  isClick: PropTypes.bool,
`isClicked` is more grammatically accurate.

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +            <path d="M2.24814 50.7004C-2.18305 34.163 7.631 17.1645 24.1685 12.7333L63.2996 2.24814C79.837 -2.18305 96.8355 7.631 101.267 24.1685L111.752 63.2996C116.183 79.837 106.369 96.8355 89.831
`stroke-width` should `strokeWidth`

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +  border: 1px solid #ffffff;
The border on `avatar-circle` causes it to be two pixels too big. Add a `box-sizing: border-box` to fix this.

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  const circleClass = !isClick ? "avatar-circle" : "avatar-circle avatar-circle-clicked";
Should this be `avatar__circle` because it's part of the avatar block.

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +  .avatar-circle-clicked {
Would `.avatar-circled_clicked` be more to BEM guidelines?

2021-01-17 04:55 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +.avatar {
Going by what I can see in storybook, the avatar is slightly too big:
![image](https://user-images.githubusercontent.com/43496356/104831302-2582fe80-584d-11eb-8806-76cfaf2098e1.png)

2021-01-18 04:56 UTC, iceicery commented
I made some change of how to handle image based on https://stackoverflow.com/questions/3796025/fill-svg-path-element-with-a-background-image. I did this for making adjustment of the layout easier. And I added span to show alt. Thanks!

2021-01-18 06:03 UTC, makstheimba commented on src/components/Avatar/Avatar.css
> +  .avatar__square_item_shift {
This class name with properties seems to be duplicated for all resolutions 🤔

2021-01-18 06:09 UTC, makstheimba commented on src/components/Avatar/Avatar.js
> +  shape: PropTypes.string.isRequired,
PropTypes.oneOf will be more suited here :) 
https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes
`PropTypes.oneOf(['square', 'circle']),`

2021-01-18 06:11 UTC, makstheimba commented on src/components/Avatar/Avatar.js
> +  isClicked: PropTypes.bool,
I think it'll be pretty hard to determine from outside if this component is clicked 
It'll be much easier to remove this prop and add `:active` pseudo class to avatar__circle
https://developer.mozilla.org/en-US/docs/Web/CSS/:active

2021-01-18 12:47 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +  display: none;
Your hidden class needs to look this or it won't show:
```
.avatar__hidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
```

2021-01-18 12:48 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +.avatar__hidden {
`.avatar_hidden-el` is a more descriptive name.

2021-01-18 12:54 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +          <svg width="114" height="114" viewBox="0 0 114 114" fill="none" xmlns="http://www.w3.org/2000/svg" className="avatar__square_item">
For accessibility to work correctly:
1. Place an id inside your hidden spans.
2. Place `aria-labelledby="CORRESPONDING_ALT_SPAN_ID"` inside the svgs that hold the image.

2021-01-18 12:54 UTC, julieg18 requested changes
Great job! The images match figma very well! I just found out that SVGs work differently than a typical element, and a screen reader is unable to find your hidden span. I've commented the steps to fix this.

2021-01-18 14:50 UTC, iceicery commented on src/components/Avatar/Avatar.css
> +  .avatar__square_item_shift {
I thought I could delete the duplicated item_shift class but the layout for that resolution would be no shift. Any ideas why?
![image](https://user-images.githubusercontent.com/43768912/104929968-31b0ae00-596a-11eb-9161-ebff5ef4543b.png)

2021-01-18 14:59 UTC, julieg18 commented on src/components/Avatar/Avatar.css
> +  .avatar__square_item_shift {
@iceicery Your `.avatar__square_item` class has a `top` and `left` property, which overwrites your previously declared `.avatar__square_item_shift` forcing your to redeclare your `.avatar__square_item_shift` on all resolutions.

2021-01-18 15:44 UTC, iceicery commented
Fixed. Please review when you have time. Thanks,

2021-01-18 16:29 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +          <span id="alt-span-id" className={circleAltClass}>{alt || "avatar"}</span>
This span doesn't need an id since it has no svgs.

2021-01-18 16:30 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +          <span className={squareAltClass}>{alt || "avatar"}</span>
This span is missing an id.

2021-01-18 16:42 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +                <image href={image} aria-labelledby="alt-span-id" x="-15" y="-20" width="150" height="150" />
Your aria-labelledby="alt-span-id" needs to be moved to the svg on line 18.

2021-01-18 16:46 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
Are you sure your prettier is enabled? This text is written with double quotes.

2021-01-18 16:59 UTC, iceicery commented on src/components/Avatar/Avatar.js
> +                <image href={image} aria-labelledby="alt-span-id" x="-15" y="-20" width="150" height="150" />
I thought we should put it <image/> based on https://www.w3.org/WAI/GL/wiki/Using_aria-labelledby_to_provide_a_text_alternative_for_non-text_content. Not really sure how it works. If you are sure, I could change. And do you know how to check if aria-labelledby works?

2021-01-18 17:10 UTC, iceicery commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
Good question. I thought I did. Did I miss something?
![image](https://user-images.githubusercontent.com/43768912/104945021-ae00bc80-597d-11eb-9879-d85f43b6152d.png)

2021-01-18 17:12 UTC, iceicery commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
![image](https://user-images.githubusercontent.com/43768912/104945242-03d56480-597e-11eb-8fc0-dd517ac8d884.png)

2021-01-18 17:38 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
Have you formatted the document?

2021-01-18 17:41 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +                <image href={image} aria-labelledby="alt-span-id" x="-15" y="-20" width="150" height="150" />
I have a downloaded screen reader on my computer. Also you can get an idea in google dev tools accessibility tab: 
![image](https://user-images.githubusercontent.com/43496356/104947914-0f2a8f00-5982-11eb-9f77-99864cbd188e.png)

2021-01-18 17:43 UTC, iceicery commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
What is this? I thought we have the same document while cloning the project.  I must missed somthing.

2021-01-18 17:49 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
You can format your code with VS code there is a button you push

2021-01-18 17:57 UTC, julieg18 commented on src/components/Avatar/Avatar.js
> +  const squareAltClass = image ? "avatar__hidden-el" : "avatar__square_alt";
Have you formatted with prettier before?

2021-01-18 22:44 UTC, iceicery commented
Thank you! Please take a look.

2021-01-18 23:03 UTC, julieg18 approved these changes
The sizing is perfect and the screen reader is working as it should! Fantastic job! 🥳

2021-01-18 23:06 UTC, merged