Add Logo
julieg18/iterative-landing pull request #16
Opened 2021-01-17 16:13 UTC by olivcamj

2021-01-17 17:27 UTC, julieg18 requested changes
Great job so far! I love how much attention to detail you gave! If you have any questions about my comments, feel free to message me!

2021-01-17 17:27 UTC, julieg18 commented on src/components/logo/logo.js
> +      <img className="logo logo__icon" src={logoImg} alt="Logo" />
The alt name could be more accurate like "Iterative logo icon", and "Logo label saying Iterative".

2021-01-17 17:27 UTC, julieg18 commented on src/components/logo/logo.css
> +  width: 114.26px;
Nice job on sizing accuracy!

2021-01-17 17:27 UTC, julieg18 commented on src/components/logo/logo.css
> +  .logo__text {
logo__text styling is no longer needed

2021-01-17 17:27 UTC, julieg18 commented on src/components/logo/logo.css
> +  align-self: center;
Your image doesn't complete cover your width/height area, causing you're text to be too small. Add a `object-fit: cover` to fix this.

2021-01-17 17:27 UTC, julieg18 commented on src/images/icon.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
The icon you exported has some padding in it, causing the logo to be too small on the site. (You can make your width/height bigger or I can export a new svg that doesn't have the extra padding for you if needed 😄) 
![image](https://user-images.githubusercontent.com/43496356/104850773-a9bd9c00-58b6-11eb-93a1-c363fea31663.png)

2021-01-18 17:08 UTC, olivcamj commented on src/images/icon.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Thank you for the correct image!

2021-01-18 17:22 UTC, julieg18 requested changes
Nice job! After this last thing, I should be able to approve!

2021-01-18 17:22 UTC, julieg18 commented on src/components/logo/Logo.css
> +  align-self: center;
Your `.logo__label` still needs a `object-fit: cover` to be correctly sized.

2021-01-18 17:27 UTC, olivcamj commented on src/components/logo/Logo.css
> +  align-self: center;
Great catch! I missed that earlier.

2021-01-18 17:35 UTC, julieg18 approved these changes

2021-01-18 19:11 UTC, merged