Add CommunityCard and Community component
julieg18/iterative-landing pull request #19
Opened 2021-01-19 19:08 UTC by iceicery

Please review, thanks,

2021-01-19 21:23 UTC, julieg18 requested changes
Great work so far! Open for discussion as always!

2021-01-19 21:23 UTC, julieg18 commented on src/components/Community/Community.css
> +  width: 288px;
I've noticed you've used a mixture of width and margin auto on the sides to adjust the width of the section. It would be better to place width at default and give padding at breakpoints. Otherwise your section isn't going to move very fluidly. It also causes this at 1024px: 
![image](https://user-images.githubusercontent.com/43496356/105093484-70c52900-5a68-11eb-9fa7-27ab99478cdb.png)

2021-01-19 21:23 UTC, julieg18 commented on src/components/Community/Community.css
> +    gap: 24x;
I believe this should be `gap: 24px`.

2021-01-19 21:23 UTC, julieg18 commented on src/components/CommunityCard/CommunityCard.css
> +    line-height: 24px;
Shouldn't line-height be 30px?

2021-01-19 21:23 UTC, julieg18 commented on src/components/CommunityCard/CommunityCard.css
> +.communitycard {
Love the card styling! It looks great!

2021-01-19 21:23 UTC, julieg18 commented on src/components/Community/Community.css
> +  .community__cardlist :nth-child(1) {
Nice idea using order to have the cards in the right order without having to add a min-height!

2021-01-19 21:33 UTC, iceicery commented on src/components/Community/Community.js
> +          <Icon icon={icnTwitter} link={'#'} widthPixelSizes={[32, 24, 32]} />
Do you mean change it to link="" ? I am not sure what you mean about "about:blank" I thought you take care of link at Icon component?

2021-01-19 21:36 UTC, julieg18 commented on src/components/Community/Community.js
> +          <Icon icon={icnTwitter} link={'#'} widthPixelSizes={[32, 24, 32]} />
Instead of `link="#"`, do `link="about:blank" inside `Icon`. It will open to a blank page, which make more sense than opening a new localhost:8000 page.

2021-01-19 21:41 UTC, iceicery commented on src/components/Community/Community.css
> +  width: 288px;
When I tried to set width for different screen size , I found that storybook won't show the change (but run develop does). So I came up this solution to use max-width min-width instead of width. Could you please see if that happened to you? I am very confused since there is no problems setting different width for communitycard component.

2021-01-19 21:42 UTC, iceicery commented on src/components/Community/Community.js
> +      <div className="community__container">
This is for medium and large screen size. flex the text and icon.

2021-01-19 21:44 UTC, julieg18 commented on src/components/Community/Community.css
> +  width: 288px;
The width on Storybook Tablet is set at 1112 not 1024. You aren't about to view 1024 on Storybook.

2021-01-19 22:01 UTC, iceicery commented on src/components/Community/Community.css
> +  width: 288px;
Never mind. I think I know the problem. It is the gap: 24 px you found at bellow. Thank you for catching that.

2021-01-19 22:10 UTC, iceicery commented on src/components/Community/Community.css
> +  width: 288px;
If I change line 54:min-width to width, the layout at figma would change. I seems that the width remain small like the picture. And the width for this element at figma is 1040 px but break point is 1024 which is smaller than that. Do you think I need to set a new break point for these two cards? 
![image](https://user-images.githubusercontent.com/43768912/105099131-c998bf80-5a70-11eb-806b-0193a0ca5be2.png)

2021-01-19 22:12 UTC, julieg18 commented on src/components/Community/Community.css
> +  width: 288px;
What are you setting your width to?

2021-01-19 22:14 UTC, iceicery commented on src/components/Community/Community.css
> +  width: 288px;
min-width: 672px to width:672px

2021-01-19 22:17 UTC, julieg18 commented on src/components/Community/Community.css
> +  width: 288px;
You need to take off width/min-width completely. Just add a padding of 48px in the tablets size case.

2021-01-19 22:24 UTC, iceicery commented on src/components/Community/Community.css
> +  width: 288px;
Ha, I guess I misunderstood what you mean. I thought I need to put the width back. I would try the padding way.

2021-01-19 22:44 UTC, iceicery commented on src/components/CommunityCard/CommunityCard.css
> +    line-height: 24px;
![image](https://user-images.githubusercontent.com/43768912/105103026-7412e180-5a75-11eb-9c63-9caf60d21dc1.png)

2021-01-19 22:48 UTC, julieg18 commented on src/components/CommunityCard/CommunityCard.css
> +    line-height: 24px;
Looks like it was an issue with my Figma 😄

2021-01-20 11:32 UTC, julieg18 requested changes

2021-01-20 11:32 UTC, julieg18 commented on src/components/Community/Community.js
> +    <section className="community">
HTML looks perfect!

2021-01-20 11:32 UTC, julieg18 commented on src/components/Community/Community.js
> +              widthPixelSizes={[32, 24, 32]}
I didn't notice before but the `Icon`s need a `linkDescription`

2021-01-20 11:32 UTC, julieg18 commented on src/components/Community/Community.css
> +  padding: 19px 16px 32px 16px;
Great job on updating the width! The container moves much more fluidly now!

2021-01-20 11:32 UTC, julieg18 commented on src/components/Community/Community.css
> +.community__cardlist {
Looking at the `.community__cardlist`, while the cards work fine, the screen looks kind of odd in some resolutions due to the way the cards move: 
![image](https://user-images.githubusercontent.com/43496356/105169093-a1e14000-5ae0-11eb-971b-356a90c7343e.png)
Do you think the cards would look nicer if you used `grid` to stretch the cards so that they are always in a row when you hit `768px`?

2021-01-20 21:40 UTC, julieg18 requested changes
Great job so far. Just two more things to fix!

2021-01-20 21:40 UTC, julieg18 commented on src/components/Community/Community.js
> +              linkDescription="Go to Discard"
Shouldn't this be "go to Discord"

2021-01-20 21:40 UTC, julieg18 commented on src/components/Community/Community.css
> +  flex-wrap: wrap;
Grid looks amazing! Do you need this `flex-wrap` property anymore?

2021-01-20 21:40 UTC, julieg18 commented on src/components/CommunityCard/CommunityCard.css
> +  width: 122px;
This width is causing overflow since the card is unable to fit in the grid with it added. It would be better to take off the width and margin from the description. You can just add a padding on the entire card to keep everything inside the card: 
![image](https://user-images.githubusercontent.com/43496356/105243975-6cb30d00-5b35-11eb-8ac3-df77e9dbcebd.png)

2021-01-20 22:14 UTC, julieg18 approved these changes
Awesome job!

2021-01-20 22:16 UTC, merged