Add header component
julieg18/iterative-landing pull request #22
Opened 2021-01-21 17:47 UTC by julieg18

2021-01-21 20:43 UTC, iceicery requested changes
Nice job! Beautiful layout and very clear code. I like that you set three pages at storybook making it so easy to review. I am so happy to see the page are coming up. Few questions and suggestions

2021-01-21 20:43 UTC, iceicery commented on src/components/Header/Header.js
> +      <Title size="l" title={title} />
I noticed that the price page has different margin between NavBar and Title at medium and big screen. Any idea how to fix it? Here is a thought. https://spectrum.chat/react/general/using-a-divider-component-for-spacing-instead-of-margins~e45e99da-81c2-4a3e-bb78-9ffa3e21083c What do you think?
![image](https://user-images.githubusercontent.com/43768912/105405310-a1d06580-5bf0-11eb-87b8-0905aef06bff.png)

2021-01-21 20:43 UTC, iceicery commented on src/components/Header/Header.stories.js
> +  title: 'Open platform to operationalize AI',
Add a &nbsp; to match the layout. ![image](https://user-images.githubusercontent.com/43768912/105406856-9b42ed80-5bf2-11eb-8607-5563273d0f80.png)

2021-01-21 20:43 UTC, iceicery commented on src/components/Header/Header.css
> +  .header__text {
.header padding-left looks different by pages @768px. Do you think we need set a text width for pricing and about pages?

2021-01-21 21:02 UTC, julieg18 commented on src/components/Header/Header.js
> +      <Title size="l" title={title} />
A divider component makes sense but forces extra unneeded divs. A prop for margin doesn't add extra elements. It's rather strange that the pricing page has a unique set of margins for the heading... I'd like to ask Maksim Kulichenko before I update anything.

2021-01-21 21:04 UTC, julieg18 commented on src/components/Header/Header.stories.js
> +  title: 'Open platform to operationalize AI',
Great Idea!

2021-01-21 21:13 UTC, julieg18 commented on src/components/Header/Header.css
> +  .header__text {
I'd like to ask Maksim Kulichenko as well, since the inconsistency is odd.

2021-01-22 11:58 UTC, julieg18 commented on src/components/Header/Header.js
> +      <Title size="l" title={title} />
Ok, the extra margin was a mistake in the design.

2021-01-22 11:59 UTC, julieg18 commented on src/components/Header/Header.css
> +  .header__text {
Ok, we need to add line breaks in the text.

2021-01-22 14:47 UTC, iceicery requested changes
Great job for fixing and adding line break! Header part looks fantastic! We probably need to add line break for Pricing page, too. Maybe the designer want the text looks more balance?
![image](https://user-images.githubusercontent.com/43768912/105504853-dcd4a680-5c8d-11eb-9208-da33359000ee.png) 
![image](https://user-images.githubusercontent.com/43768912/105504916-ed851c80-5c8d-11eb-8b1b-ec59c3279e22.png)

2021-01-22 15:34 UTC, iceicery approved these changes
Great job!!

2021-01-22 15:35 UTC, merged