Add CustomersList component
julieg18/iterative-landing pull request #23
Opened 2021-01-21 18:06 UTC by iceicery

Please review.

2021-01-21 21:57 UTC, julieg18 requested changes
Great job so far! The tablet and desktop sizes are perfectly spaced!

2021-01-21 21:57 UTC, julieg18 commented on src/components/CustomersList/CustomersList.css
> +  margin: 0;
You're gonna need to add margin top since the button above it has no margin bottom.

2021-01-21 21:57 UTC, julieg18 commented on src/components/CustomersList/CustomersList.css
> +  row-gap: 0;
Is the `row-gap` needed?

2021-01-21 21:57 UTC, julieg18 commented on src/components/CustomersList/CustomersList.js
> +export default function CustomersList() {
HTML markup looks great!

2021-01-21 21:57 UTC, julieg18 commented on src/components/CustomersList/CustomersList.css
> +.customerslist__item {
Hmmm it looks like your second row of icons appears to be too high on the phone size: 
![image](https://user-images.githubusercontent.com/43496356/105416700-28407380-5c00-11eb-902f-14c0a7307866.png)
Maybe you can add some top `margin` to `.customerslist__item` 🤔

2021-01-21 22:09 UTC, iceicery commented on src/components/CustomersList/CustomersList.css
> +@media (min-width: 341px) {
I am adding padding to make sure it remains three items at a line. And the padding need to be bigger for screen greater than 341px. The layout for less than 414 should look the same.

2021-01-21 22:09 UTC, iceicery commented on src/components/CustomersList/CustomersList.css
> +  margin: 0;
Sure! I also noticed that when looking at the Header component.

2021-01-21 22:12 UTC, julieg18 commented on src/components/CustomersList/CustomersList.css
> +@media (min-width: 341px) {
That makes sense, but I feel like there is a better way to do this. 🤔 I'll look into it.

2021-01-22 11:41 UTC, julieg18 requested changes
Everything looks perfect! Great job! Just delete the `linkDescriptions` and you'll be able to merge!

2021-01-22 11:41 UTC, julieg18 commented on src/components/CustomersList/CustomersList.js
> +          linkDescription="Smithsonian"
Icons aren't links so they don't need linkDescription.

2021-01-22 13:50 UTC, julieg18 approved these changes
Approved!

2021-01-22 14:08 UTC, merged