Add CompanyHighlight and CompanyHighlightList Component.
julieg18/iterative-landing pull request #25
Opened 2021-01-22 16:15 UTC by iceicery

Please review. Thanks,

2021-01-22 21:52 UTC, julieg18 requested changes
It looks amazing!

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlight/CompanyHighlight.js
> +        <h4 className="companyhighlight__title">{title}</h4>
Since the companyHighlight is inside a section, which has an `h2` , should this be an `h3`?

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +  padding: 0 16px;
The company hightlight sits inside a section, which will provide the padding on the sides.

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +  display: grid;
Nice use of grid! Everything flows really easily and the code is simple!

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +    grid-template-columns: repeat(3, 1fr);
When you use `1fr` the columns split unevenly, causing each column to be slightly different: 
![image](https://user-images.githubusercontent.com/43496356/105551328-3063e600-5cc8-11eb-9e63-e42cbb14cccf.png)
To fix this, replace line 14 with ` grid-template-columns: repeat(3, minmax(0, 1fr));` [For more info](https://css-tricks.com/equal-width-columns-in-css-grid-are-kinda-weird/)

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +    margin: 140px 0 80px;
I believe the margin needs to be `80px 0`: 
![image](https://user-images.githubusercontent.com/43496356/105552136-21316800-5cc9-11eb-887f-44bd2c19e0ac.png)
Note: The diagram requires the extra padding for their background gradient.

2021-01-22 21:52 UTC, julieg18 commented on src/components/CompanyHighlight/CompanyHighlight.css
> +  line-height: 28px;
Nice job on the fonts! It's all correct as far as I can tell!

2021-01-22 22:27 UTC, iceicery commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +    grid-template-columns: repeat(3, 1fr);
Nice trick! Glad that I could learn new thing.

2021-01-22 22:27 UTC, iceicery commented on src/components/CompanyHighlightList/CompanyHighlightList.css
> +  padding: 0 16px;
Thanks for pointing it out. I thought company-highlight is a section but now I see it should be in Enterprise section.

2021-01-22 22:27 UTC, iceicery commented on src/components/CompanyHighlight/CompanyHighlight.js
> +        <h4 className="companyhighlight__title">{title}</h4>
The SectionTitle I am working on has title,(h2) subtitle(h3), text(p). Based on the font-size, the Enterprise section has title and subtitle. So what do you think? I have no preference.
![image](https://user-images.githubusercontent.com/43768912/105554659-69528980-5ccd-11eb-95fa-5c10b6da056b.png)

2021-01-22 23:04 UTC, julieg18 commented on src/components/CompanyHighlight/CompanyHighlight.js
> +        <h4 className="companyhighlight__title">{title}</h4>
Oh, I see. I thought is was text, but definitely could read as subtitle..

2021-01-23 16:05 UTC, julieg18 approved these changes
Fantastic job! Everything looks awesome!

2021-01-23 16:10 UTC, merged