Add WorldMap and Team Component
julieg18/iterative-landing pull request #37
Opened 2021-01-28 22:13 UTC by iceicery

I am using React Simple Maps for WorldMap:  https://www.react-simple-maps.io/docs/getting-started/ . I tried to rotate and resize the map. But it is still not exactly like the design.
I use avatar as my marker based on :https://www.react-simple-maps.io/examples/custom-markers/ , However only svg could be the marker, so I couldn't use the Avatar component we made. I have some problems adjusting avatar marker size to fit the Figma design. It seems that the marker size would change with the map size change. 
I change the map background based on https://codesandbox.io/s/map-chart-with-texture-yjs2y?file=/src/MapChart.js.
I feel the document for react-simple-map is not very complete so maybe this will help.https://github.com/zcreativelabs/react-simple-maps

 Doing the map is fun but is quite new to me. Let's learn together!

2021-01-29 13:43 UTC, julieg18 requested changes
The map config still appears too high. The only way I could adjust it was giving it a negative margin bottom. Let me know if you want to discuss any of my comments!

2021-01-29 13:53 UTC, julieg18 commented on src/components/Team/Team.css
> +.team {
The team section looks great!

2021-01-29 13:53 UTC, julieg18 commented on src/components/WorldMap/WorldMap.js
> +      <DeveloperCard
Could we also add a transition when the card appears.

2021-01-29 14:28 UTC, iceicery commented on src/components/WorldMap/WorldMap.js
> +        onClick={closeDeveloperCardPopup}
That is what I think originally. I tried the following code. The problem is sometime the card will popup covering that marker and the computer thinks the mouse leaves so the card will non-stop opening and closing even if the mouse is not moving. Any idea?  ![image](https://user-images.githubusercontent.com/43768912/106286071-dce32200-620a-11eb-8cb2-3f970daca315.png)

2021-01-29 14:30 UTC, iceicery commented on src/components/WorldMap/WorldMap.js
> +        onClick={closeDeveloperCardPopup}
I saw the review bellow. I guess if I did the card under the marker. The problem will be solved.

2021-01-29 14:31 UTC, julieg18 commented on src/components/WorldMap/WorldMap.js
> +        onClick={closeDeveloperCardPopup}
Yes, it would! You could keep the card centered in the middle(so their is no risk of it overflowing on the sides) and adjust the top to be below the hover marker!

2021-01-29 21:19 UTC, julieg18 requested changes
Great job! The card hover looks much better and the map has improved significantly!

2021-01-29 21:19 UTC, julieg18 commented on src/components/Team/Team.css
> +    margin: 0 0 130.4px;
While I wasn't able to get it perfect, it appears that `margin: 0 0 40px` is the closest we can get to the Figma design.

2021-01-29 21:19 UTC, julieg18 commented on src/components/Team/Team.css
> +    margin: 109px 0 0;
`margin: 100 0 0;` appears to be more accurate to 768px.

2021-01-29 21:19 UTC, julieg18 commented on src/components/Team/Team.css
> +    margin: 62.96px -80px 0;
`margin: 40px -80px 0;` appears to be more accurate.

2021-01-29 21:19 UTC, julieg18 commented on src/components/Team/Team.css
> +    margin: 0 0 64px;
`margin: 0px 0 -150px;` appears to more accurate.

2021-01-29 21:29 UTC, iceicery commented on src/components/Team/Team.css
> +    margin: 0 0 64px;
Thanks for offering correct number of the margin. I was thinking of adjusting while assembling the page but I will do it right now.

2021-01-29 22:56 UTC, julieg18 requested changes
Great job, the styling is looking fantastic! Only two more things 😄

2021-01-29 22:56 UTC, julieg18 commented on src/components/WorldMap/WorldMap.js
> +        image={developerCardData.image}
The updates to DeveloperCard are changing the Leadership images:
**![image](https://user-images.githubusercontent.com/43496356/106333663-c494f680-624e-11eb-9763-7c5eac5f7cfe.png)**
![image](https://user-images.githubusercontent.com/43496356/106333682-d4acd600-624e-11eb-9d37-088bb0d29ea1.png)

2021-01-29 22:56 UTC, julieg18 commented on src/components/WorldMap/WorldMap.js
> +            setPositionY(e.clientY);
The DeveloperCard is currently set to `fixed` which causes to the card to stay as you scroll:
![image](https://user-images.githubusercontent.com/43496356/106335445-7124a780-6252-11eb-8903-4481c6f89b68.png)
I think `absolute` would look a lot cleaner. Here is way to get positioning:
![image](https://user-images.githubusercontent.com/43496356/106335607-cb256d00-6252-11eb-8b98-ea6be661821a.png)

2021-01-30 01:08 UTC, iceicery commented on src/components/WorldMap/WorldMap.js
> +        image={developerCardData.image}
Nice catch!! I know what happened here. For each image being a svg background needs a unique id. I fixed similar issue at circle mark but totally forgot the square avatars. I'll finish the price card first. 
![image](https://user-images.githubusercontent.com/43768912/106341920-902c3500-6264-11eb-9e57-2fb6503e2ee0.png)

2021-01-30 05:11 UTC, julieg18 approved these changes
Great job! Approved!

2021-01-30 05:12 UTC, merged