Add PriceCard and PriceCardList Component
julieg18/iterative-landing pull request #38
Opened 2021-01-30 04:21 UTC by iceicery

In this PR, I also add a large Button for PriceCard.  The PriceCardList could be directly in main or Header.

2021-01-30 05:03 UTC, julieg18 requested changes
Great job so far! The styling is almost perfect!

2021-01-30 05:03 UTC, julieg18 commented on src/components/PricingCardList/PricingCardList.css
> +  }
there should be a space here.

2021-01-30 05:03 UTC, julieg18 commented on src/components/PricingCardList/PricingCardList.css
> +  }
There should be a space here.

2021-01-30 05:22 UTC, iceicery commented on src/components/PricingCardList/PricingCardList.js
> +            <Icon
How about the Icon link feature? Do you mean like <a><Icon ..(no link)/>Go to CML</a> ? How about the hover style?

2021-01-30 19:45 UTC, julieg18 requested changes
Nice job! Just one more thing and we should be able to finish the page!

2021-01-30 19:45 UTC, julieg18 commented on src/components/PricingCardList/PricingCardList.css
> +.pricing-card-list__link-item:hover {
Nice job on adding hover animations! It would be better for the hover animations to be placed on `.pricing-card-list__link`  instead of `.pricing-card-list__link-item` and `.pricing-card-list__link-viewer`. Otherwise non clickable parts look like clickable parts.

2021-01-31 00:02 UTC, julieg18 approved these changes
Awesome job! 👏

2021-01-31 00:16 UTC, merged