Assemble about page.
julieg18/iterative-landing pull request #39
Opened 2021-01-30 18:00 UTC by iceicery

In this PR, I put some component together and add margin to fit the design. However, I was unable to fix the TimeLine issue I found while assembling the page. Please take a look.

2021-01-30 20:54 UTC, julieg18 requested changes
Awesome job putting everything together! Message me if you need any help!

2021-01-30 20:54 UTC, julieg18 commented on src/pages/about.js
> +        <TimeLine times={times} />
To correct timeline error, change Header.css line 63 from `.header .title {` to `.header .title_size_l {`

2021-01-30 20:54 UTC, julieg18 commented on src/components/Team/Team.css
> +  margin: 40px 0 40px;
`margin: 38px 0 40px is more accurate`

2021-01-30 20:54 UTC, julieg18 commented on src/components/Team/Team.css
> +    margin: 40px 0 40px;
`margin: 60px 0 60px` appears to be more accurate.

2021-01-30 20:54 UTC, julieg18 commented on src/components/Leadership/Leadership.css
> +    margin: 46px 0 0;
`margin: 0` appears to most accurate.

2021-01-31 02:48 UTC, iceicery reviewed
Thanks for taking care of this. The page looks great and functional.  Nice job!

2021-01-31 02:48 UTC, iceicery commented on src/components/Header/Header.css
> +  .header .title_size_l {
Interesting. So, how the issue happened? I don't get it.

2021-01-31 02:48 UTC, iceicery commented on src/pages/about.js
> -export default function AboutPage({ onClick }) {
Ops. I totally forgot we are using gastby. I was in the OLD REACT mind. Good job adding these functions. The form acts perfectly.

2021-01-31 02:51 UTC, julieg18 approved these changes

2021-01-31 02:52 UTC, merged