Update timeline
julieg18/iterative-landing pull request #76
Opened 2021-02-03 15:48 UTC by julieg18

* remove extra time width on phone size
* take off extra margin/padding
* take off final time line
* add phone time line svg
* fix cursor in tablet/desktop

2021-02-03 20:52 UTC, iceicery requested changes
Nice job fixing the timeline. It looks great. Only two comments, please take a look.

2021-02-03 20:52 UTC, iceicery commented on src/components/TimeLine/TimeLine.css
> -  margin: 40px -16px 0;
I am not sure we need to change this. Is the design changed? 
![image](https://user-images.githubusercontent.com/43768912/106804891-9d15a380-662b-11eb-8be8-6ded6972b9f6.png)

2021-02-03 20:52 UTC, iceicery commented on src/components/TimeLine/TimeLine.css
> +    background-image: url(../../images/timeline-line.svg);
We probably need a timeline-line-tablet.svg, too. Lines are shown behind year numbers.
![image](https://user-images.githubusercontent.com/43768912/106805976-fe8a4200-662c-11eb-9856-e73fa28c8bfd.png)

2021-02-03 21:15 UTC, julieg18 commented on src/components/TimeLine/TimeLine.css
> -  margin: 40px -16px 0;
We no longer need the the time line to stretch past the sides of the site, so no reason to add extra margin and padding.

2021-02-03 21:15 UTC, julieg18 commented on src/components/TimeLine/TimeLine.css
> +    background-image: url(../../images/timeline-line.svg);
I'll add a tablet SVG!

2021-02-03 21:35 UTC, iceicery commented on src/components/TimeLine/TimeLine.css
> -  margin: 40px -16px 0;
I see. I wonder if the map design is also changed: About Map Desktop: Reduce the map size (design oversight, TBD) #69. Does that mean we don't need to stretch our map past the sides of the site, either?

2021-02-03 21:36 UTC, julieg18 commented on src/components/TimeLine/TimeLine.css
> -  margin: 40px -16px 0;
TBD means to be decided. So we need to wait to see what the designer wants exactly for the map.

2021-02-04 04:04 UTC, iceicery requested changes
Code looks good. Did you add the svg file for tablet?

2021-02-04 12:00 UTC, julieg18 commented on src/components/TimeLine/TimeLine.css
> +    background-image: url(../../images/timeline-line-tablet.svg);
Whoops, forgot to commit it 😅

2021-02-04 14:23 UTC, iceicery approved these changes
Nice job!

2021-02-04 14:49 UTC, merged